### ISSUE TITLE
Logo proposal for Gavel 

### ISSUE THREAD

**Issue by memoryskull** [williamleiby/gavel#39]
Hi good day @williamleiby 
I am a graphic designer and I would like to contribute with the project
I can offer a logo that represents the project.
You can receive the logo without any commitment.
I want to contribute because I like to do it.
Thanks for your time.

Cheers!

**Comment by williamleiby** [comment]
@memoryskull Thank you very much for your interest in Gavel! You're more than welcome to design a logo for this project. Shoot me an email at william@williamleiby.com so we can talk more.
